Repository quicwg/ops-drafts, pull requests merged in 2021-02, with the labels that each got.

#220 clarify that ports are advisory for the network
  draft-ietf-quic-manageability.md
Labels: ready-to-merge

#225 Editorial rollup for applicability
  draft-ietf-quic-applicability.md
Labels: ready-to-merge

#228 Ordered and reliable will be assumed
  draft-ietf-quic-applicability.md
Labels: ready-to-merge

#229 Less encrypted; more correct about HTTP
  draft-ietf-quic-manageability.md
Labels: editorial, ready-to-merge

#223 Editorial nits from @gorryfair, thanks!
  draft-ietf-quic-manageability.md
Labels: ready-to-merge

#224 Editorial comments from @seanturner, thanks!
  draft-ietf-quic-manageability.md
Labels: ready-to-merge

#250 Fix section reference to QUIC-http ALPN
  draft-ietf-quic-applicability.md
Labels: editorial, ready-to-merge

#252 clarify 10 0-RTT packets in first round
  draft-ietf-quic-manageability.md
Labels: editorial, ready-to-merge

#254 Version negotiation
  draft-ietf-quic-manageability.md
Labels: ready-to-merge

#259 Add a sentence on taps
  draft-ietf-quic-applicability.md
Labels: ready-to-merge

#261 Tighten up language around 0-RTT
  draft-ietf-quic-applicability.md
Labels: ready-to-merge

#221 Clarify and reference spinbit optional/version
  draft-ietf-quic-manageability.md
Labels: ready-to-merge

#255 might eventually be able to associate the version...
  draft-ietf-quic-manageability.md
Labels: editorial

#268 Editorial notes from applicability read-through
  draft-ietf-quic-applicability.md
Labels: -applicability
